{% set name = "fluidfoam" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 111f86b8316cb42d60ac71085488ed1ae7360d831e472bd35320b1c3888ae075

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - python >=3.8
    - numpy >=1.11
    - scipy >=1.7.3
    - matplotlib-base >=1.5
    - netCDF4

test:
  imports:
    - fluidfoam

about:
  home: https://bitbucket.org/fluiddyn/fluidfoam
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Openfoam PostProcessing Python Tools

extra:
  recipe-maintainers:
    - CyrilleBonamy
