{% set name = "fluidfoam" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 07ea0668a0dd87300d7f3d349401bde0575314b1a5cd9c2aa9fb94d8d9de6c28

build:
  number: 0

  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.11
    - scipy >=1.7.3
    - matplotlib-base >=1.5
    - netCDF4

test:
  requires:
    - python {{ python_min }}
  imports:
    - fluidfoam

about:
  home: https://github.com/fluiddyn/fluidfoam
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Openfoam PostProcessing Python Tools

extra:
  recipe-maintainers:
    - CyrilleBonamy
